spring.application.name=RESTApi
spring.ai.openai.api-key = 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
spring.ai.openai.base-url= https://openrouter.ai/api
spring.ai.openai.chat.options.model= google/gemma-3-4b-it:free
spring.ai.openai.embedding.enabled=false
